#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
require 'vendor/autoload.php';

$app = new Application('Terminal todo App', '1.0');

try
{
    $pdo = new PDO('mysql:host=localhost;dbname=tasks', 'root', 'secret');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch (Exception $exception)
{
    echo 'Could not connect to database';
    exit();
}

$dbHook = new Acme\DatabaseHook($pdo);
$app->add(new Acme\ShowCommand($dbHook));
$app->add(new Acme\AddCommand($dbHook));
$app->add(new Acme\CompleteCommand($dbHook));

$app->run();
